### PR TITLE
Feature: Add part name

### PR DESCRIPTION
**Pull request by Bouni**
This PR is meant to work together with PR https://github.com/ModischFabrications/CutSolver/pull/60 and allows to enter a part name per item which is then displayed on the cut list.

Screenshot 2024-01-19 142800

### CODE REVIEW

**Comment by ModischFabrications** [comment]
Test seem to fail because of invalid test setup, do they work locally for you? Build error points to outdated axios import style, but I've become a bit rusty.

**Comment by Bouni** [comment]
Have to check tomorrow

**Comment by Bouni** [comment]
With `npm run test:unit` all tests succeed for me locally:

```
Test Suites: 1 passed, 1 total
Tests:       6 passed, 6 total
Snapshots:   0 total
Time:        17.65 s
Ran all test suites.
```

But I see a ton of warnings and deprecation warnings

**Comment by Bouni** [comment]
Ok, I can reproduce the error. If I run `npm ci` it installes packages I guess (not sure) and afterwards `npm run test:unit` I get the same error as the GH action shows.

After some seraching I fount this jest issue: https://github.com/axios/axios/issues/5101#issuecomment-1288382863

When I add the suggested solution to the `jest.config.js` it works as before.

I've no idea why it worked in the first place for me 😅

Anyway, I just pushed that change and it should run in the CI as well now

**Comment by Bouni** [comment]
@ModischFabrications Anything I missed? Would you mind approve a CI run to see if things are right now?

**Comment by ModischFabrications** [comment]
CI seems to work now, good work 👍🏻
Not sure why I need to approve all runs, might look into it later

**Comment by Bouni** [comment]
So do you plan to merge this one as well as https://github.com/ModischFabrications/CutSolver/pull/60 soon?

**Comment by ModischFabrications** [comment]
Yes, the next few evenings.

**Comment by Bouni** [comment]
Nice 😎

**Comment by ModischFabrications** [comment]
Also promoted with updated CI here, but the multiarch build seems to take forever. Let's hope it goes through, I would need to exclude non-x64 platforms otherwise.

**Pull request merged**
